export const animalEnemies: Record<string, EnemyStats> = {
  wolf: {
    stringComplexity: 5,
    regeneration: 0,
    health: 150,
    speed: 0.8,
    damage: 30,
    armor: 10,
    size: 4,
    spawn: 5,
    resistance: {
      debuff: 10,
      stun: -10,
      fire: -5,
      cold: 5,
      lightning: 0,
      poison: -15,
      physical: 5,
    },
    sprite: "/sprites/animals/wolf.png",
  },
  bear: {
    stringComplexity: 8,
    regeneration: 10,
    health: 200,
    speed: 0.5,
    damage: 40,
    armor: 15,
    size: 6,
    spawn: 4,
    resistance: {
      debuff: 5,
      stun: 10,
      fire: 0,
      cold: 15,
      lightning: -5,
      poison: 10,
      physical: 7,
    },
    sprite: "/sprites/animals/bear.png",
  },
  snake: {
    stringComplexity: 3,
    regeneration: 0,
    health: 100,
    speed: 0.9,
    damage: 15,
    armor: 5,
    size: 3,
    spawn: 7,
    resistance: {
      debuff: -20,
      stun: -25,
      fire: -10,
      cold: -5,
      lightning: 5,
      poison: 25,
      physical: 3,
    },
    sprite: "/sprites/animals/snake.png",
  },
};
